using Lintelligent.AnalyzerEngine.Abstractions;
using Lintelligent.AnalyzerEngine.Results;

namespace Lintelligent.AnalyzerEngine.Rules;

public class MagicNumberRule : IAnalyzerRule
{
    public string Id => "LNT004";
    public string Description => "Numeric literals should be replaced with named constants";
    public Severity Severity => Severity.Info;
    public string Category => DiagnosticCategories.CodeSmell;

    private static readonly HashSet<string> ExcludedValues = ["0", "1", "-1"];

    public IEnumerable<DiagnosticResult> Analyze(SyntaxTree tree)
    {
        if (IsGeneratedCode(tree))
            yield break;

        var root = tree.GetRoot();
        var numericLiterals = root.DescendantNodes()
            .OfType<LiteralExpressionSyntax>()
            .Where(lit => lit.IsKind(SyntaxKind.NumericLiteralExpression));

        foreach (var literal in numericLiterals)
        {
            var literalValue = literal.Token.ValueText;

            // Exclude 0, 1, -1
            if (ExcludedValues.Contains(literalValue))
                continue;

            // Exclude if part of a const declaration
            if (IsPartOfConstDeclaration(literal))
                continue;

            var line = literal.GetLocation().GetLineSpan().StartLinePosition.Line + 1;
            var message = $"Magic number '{literalValue}' should be replaced with a named constant. " +
                         "Consider extracting to a const field or readonly property.";

            yield return new DiagnosticResult(
                tree.FilePath,
                Id,
                message,
                line,
                Severity,
                Category
            );
        }
    }

    private static bool IsPartOfConstDeclaration(SyntaxNode node)
    {
        var current = node.Parent;

        while (current != null)
        {
            switch (current)
            {
                // Check if we're in a const field declaration
                case FieldDeclarationSyntax fieldDecl when
                    fieldDecl.Modifiers.Any(SyntaxKind.ConstKeyword):
                // Check if we're in a const local declaration
                case LocalDeclarationStatementSyntax localDecl when
                    localDecl.Modifiers.Any(SyntaxKind.ConstKeyword):
                    return true;
                default:
                    current = current.Parent;
                    break;
            }
        }

        return false;
    }

    private static bool IsGeneratedCode(SyntaxTree tree)
    {
        var fileName = Path.GetFileName(tree.FilePath);
        if (fileName.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase) ||
            fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
            fileName.Contains(".Generated."))
            return true;

        var root = tree.GetRoot();
        var leadingTrivia = root.GetLeadingTrivia().Take(10);
        return leadingTrivia.Any(t => 
            t.ToString().Contains("<auto-generated>") ||
            t.ToString().Contains("<auto-generated />"));
    }
}
